### ISSUE TITLE
Failover for Context Service 

### ISSUE THREAD

**Issue by lisafast** [lisafast/react-answers#39]
Answer service fails over to one of the other AI's (in ChatAppContainer) but ContextService does not. 
Need to add endpoint for gpt-4o-mini-2024-07-18 (or maybe can just put gpt-4o-mini - not clear from this model page https://platform.openai.com/docs/models/gp#gpt-4o-mini )
And then add failover logic

**Comment by ryanhyma** [comment]
Fixed and test here: https://react-answers-p28r3jahg-test-canada.vercel.app/

**Comment by ryanhyma** [comment]
Fixed.
