### ISSUE TITLE
AgenticBase ignores system prompt

### ISSUE THREAD

**Issue by lisafast** [lisafast/react-answers#60]
I continue to be concerned about the changes over the last weeks in terms of how some key tasks are degraded.  I tried an experiment of switching back to base.js to see if it was agenticBase that was causing this, but it didn't change anything.  It's possible it's the search results. When the user is misguided/misunderstanding or the system prompt instructions say they should always use a wizard, the search results skip the wizard and provide the incorrect links in a way that the AI instructions and AI avoid.  

It just seems to be ignoring much of the system prompt instructions that it faithfully applied throughout the month of November.We have many examples of excellent answers for key department scenarios (like this visa question)  - perhaps what I need to do is provide those as examples in the system prompt. I had previously done this to good effect. If I have time today, I'll try that. 

Here's a good example, broken down. 
1. Introductory phrase not in tags - ignores that system prompt says no intro phrases, AND no text outside of tags, intro phrases were very rare until recently
2. Intro phrase is in first person 'let me check' - ignores that system prompt says no first person - no first person phrases were seen in responses until recently  
3. Response answers VISA question directly - ignores direct instruction in ircc-scenarios.js to never answer visa questions directly becuase there are so many factors in the decision. Therefore the answer is incorrect and scores 0. The instructions say: 
```
## Immigration and visiting Canada 
* Visa/eTA Inquiries: Visa and ETA decisions are based on a number of factors, including the user's nationality, the purpose of their visit, and the country they are visiting. Direct users to the "Find out if you need a visa to enter Canada" page which will walk them through a set of questions to get an answer for their situation: https://ircc.canada.ca/english/visit/visas.asp 
```
4. The citation link is to the visas page instead of the directed citation in the instructions to check if they need a visa or eTA. 
5. Finally in the follow on response, the citation url is hallucinated for the eTA page (which is one of the most heavily used pages on canada.ca ) and replaced with a search results link fallback. Also score of 0. 
![image](https://github.com/user-attachments/assets/0ca03aa3-7e42-437e-9ddb-38f7d7d8ae06)

**Comment by lisafast** [comment]
I added some more examples to the ircc-scenarios and to scenarios-all to try and give it a better idea of 'golden answers'.

**Comment by lisafast** [comment]
Another example of the citation link being replaced or lost instead of it using the link from the prompt. 
![IMG_1914](https://github.com/user-attachments/assets/d399132f-5853-4d07-9265-501de00c70bb)

**Comment by ryanhyma** [comment]
When I look at ClaudeService.js and  ChatGPTService.js 
It passes all of the context data:
What is SCIS?\n<department>ISC</department>\n<topic>Indian status and status cards</topic>\n<topicUrl>https://www.sac-isc.gc.ca/eng/1100100032374</topicUrl>\n<departmentUrl>https://www.canada.ca/en/indigenous-services-canada.html</departmentUrl>\n<searchResults>\n{\n  "results": [\n    {\n      "link": "https://www.sac-isc.gc.ca/eng/1462806841047/1572461062751",\n      "linkText": "Application forms for Indian status and status cards",\n      "summary": "Nov 15, 2024 ... ... (SCIS) (for children 15 years …mitted securely to Indigenous Services Canada. The SCIS ..."\n    },\n    {\n      "link": "https://www.sac-isc.gc.ca/DAM/DAM-ISC-SAC/DAM-INSTS/STAGING/texte-text/seccertindstatus_INTER-83-172instr_1554737179608_eng.pdf",\n      "linkText": "INTRUCTIONS - APPLICATION FOR ALREADY REGISTERED",\n      "summary": "... SCIS Photo App or the back of 1 printed photo. Send the application and all required documents to: National SCIS Processing Unit. Indigenous Services Canada."\n    }\n  ]\n}\n</searchResults>'

in message, which would be considered as being after the departmental stuff.

I could rework the class to extract the context data and load it into the system prompt before the updates and scenarios. 
Or update the loadSystemPrompt to add language around the updates that would take precendence over what is contained in the context.

**Comment by ryanhyma** [comment]
Hi Lisa, you were right about the order, the context is now added into the system prompt, above the departmental scenarios/updates, instead of in the user message. I'm able to get correct answers now based on the India question

**Comment by lisafast** [comment]
Fantastic! Good thing to learn. 
![image](https://github.com/user-attachments/assets/1f4b8680-0b17-4f8b-8814-af7aca9a2067)
